services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /mnt/second/docker/paperless-redisdata:/data

  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - /mnt/second/docker/paperless-pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - /mnt/second/docker/paperless-data:/usr/src/paperless/data
      - /mnt/second/docker/paperless-media:/usr/src/paperless/media
      - /mnt/second/docker/paperless-export:/usr/src/paperless/export
      - /mnt/second/docker/paperless-consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
