networks:
  default:
    name: selfhosted

services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    networks:
      - default
    ports:
    - 8096:8096
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=jellyfin"
      - "docktail.service.port=8096"
      - "docktail.service.service-port=443"
    volumes:
      - /mnt/second/docker/jellyfin-config:/config
      - /mnt/second/docker/jellyfin-cache:/cache
      - /mnt/first/home/q/files/media:/media/main
      - /mnt/second/media:/media/disk
      - ~/files/media/Shows/:/nvme/media/Shows
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri:/dev/dri
